### PR TITLE
Maintain guix-install.sh (Fix #20)

### LINKED ISSUE #20: Broken since February 2023
The `Install Guix` phase has recently started failing with

```
[1677520229.916]: [ INFO ] Linking the root user's profile
[1677520230.118]: [ PASS ] activated root profile at /root/.config/guix/current
[1677520230.169]: [ PASS ] group <guixbuild> created
[1677520230.173]: [ INFO ] group kvm exists and build users will be added to it
[1677520230.246]: [ PASS ] user added <guixbuilder01>
[1677520230.270]: [ PASS ] user added <guixbuilder02>
[1677520230.297]: [ PASS ] user added <guixbuilder03>
[1677520230.339]: [ PASS ] user added <guixbuilder04>
[1677520230.375]: [ PASS ] user added <guixbuilder05>
[1677520230.420]: [ PASS ] user added <guixbuilder06>
[1677520230.452]: [ PASS ] user added <guixbuilder07>
[1677520230.479]: [ PASS ] user added <guixbuilder08>
[1677520230.512]: [ PASS ] user added <guixbuilder09>
[1677520230.542]: [ PASS ] user added <guixbuilder10>
Created symlink /etc/systemd/system/guix-daemon.service.wants/gnu-store.mount → /etc/systemd/system/gnu-store.mount.
Unit /etc/systemd/system/gnu-store.mount is added as a dependency to a non-existent unit guix-daemon.service.
Created symlink /etc/systemd/system/multi-user.target.wants/guix-daemon.service → /etc/systemd/system/guix-daemon.service.
[1677520232.146]: [ PASS ] enabled Guix daemon via systemd
[1677520232.149]: [ INFO ] making the guix command available to other users
[1677520232.474]: [ PASS ] Authorized public key for ci.guix.gnu.org
[1677520232.632]: [ PASS ] Authorized public key for bordeaux.guix.gnu.org
[1677520232.647]: [ PASS ] installed shell completion
[1677520232.701]: [ PASS ] Bash shell prompt successfully customized for Guix
[1677520232.703]: [ INFO ] cleaning up /tmp/guix.KiwyEv
[1677520232.705]: [ PASS ] Guix has successfully been installed!
[1677520232.707]: [ INFO ] Run 'info guix' to read the manual.
[1677520232.709]: [ INFO ] Please log out and back in to complete the installation.
yes: standard output: Broken pipe
Error: Unable to process file command 'env' successfully.
Error: Access to the path '/home/runner/work/_temp/_runner_file_commands/set_env_ce49b965-d6e4-4c91-8f30-d2ab253d8be5' is denied.
Error: Unable to process file command 'state' successfully.
Error: Access to the path '/home/runner/work/_temp/_runner_file_commands/save_state_ce49b965-d6e4-4c91-8f30-d2ab253d8be5' is denied.
Error: Unable to process file command 'output' successfully.
Error: Access to the path '/home/runner/work/_temp/_runner_file_commands/set_output_ce49b965-d6e4-4c91-8f30-d2ab253d8be5' is denied.
Error: Unable to process file command 'env' successfully.
Error: Access to the path '/home/runner/work/_temp/_runner_file_commands/set_env_00feac3d-a6fe-4153-b14f-0323783bb262' is denied.
Error: Unable to process file command 'state' successfully.
Error: Access to the path '/home/runner/work/_temp/_runner_file_commands/save_state_00feac3d-a6fe-4153-b14f-0323783bb262' is denied.
Error: Unable to process file command 'output' successfully.
Error: Access to the path '/home/runner/work/_temp/_runner_file_commands/set_output_00feac3d-a6fe-4153-b14f-0323783bb262' is denied.
```

I presume it's due to a change in the GitHub CI API.  @PromyLOPh Any idea?

### PR DESCRIPTION
**Pull request by TxGVNN**
I would like to create this PR to resolve #20 by maintaining guix-install.sh. I pined version is 1.4.0

I tested on my repository https://github.com/TxGVNN/giaelpa/actions/runs/4485553955/jobs/7887221072

If you think it is fine, we need to update this line to this repo [action.yml#L36](https://github.com/TxGVNN/guix-install-action/blob/37e62acae8bbe0d4dc0ffebad5af0b5d9b0570bb/action.yml#L36) (you can tell me), after that we can squash and merge.
Other side, feel free to close if you had any plan.

Thanks

### CODE REVIEW

**Comment by jmercouris** [comment]
Fantastic work :-)

**Comment by PromyLOPh** [comment]
While I think that maintaining our own guix-install.sh is the only way forward right now I’m sceptical pinning Guix to 1.4.0 is a good idea, since it’ll increase pull times significantly. Where is that guix-install.sh from?

**Comment by TxGVNN** [comment]
I apologize if I misunderstood. The `guix-install.sh` file I used was downloaded from your settings. I think pinning Guix to version 1.4.0 would affect only the Guix binary and not `guix pull`.

**Comment by ph** [comment]
I think having a custom `sh` is the only forward but I wonder if we should instead limit the code that we have to keep in this repository and instead use a similar strategy as the Guix packaging does in some cases  and keep a `patch` file that we apply on the `guix-install.sh` after downloading it.

I assume we could have a CI job defined in this repository that could periodically apply the patch to the `guix-install.sh` file and raise an error if it fail.

**Comment by TxGVNN** [comment]
Yes, I ever think about using patch file. Thank you, @ph, I migrated to use patch file instead.
And I pin guix-install.sh by download with hash commit.

**Comment by jmercouris** [comment]
I think this looks OK to merge, no?

**Comment by TxGVNN** [comment]
I replace the static URL by using ENV from github action. Although, [github docs](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) mention `GITHUB_ACTION_REPOSITORY` but it is empty, so I extracted from `GITHUB_ACTION_PATH`. Now, it is ready to merge.

**Comment by jmercouris** [comment]
Interestingly it fails on my fork, https://github.com/atlas-engineer/guix-install-action/actions/runs/4513937405

not sure why that is.

**Comment by TxGVNN** [comment]
Could you show log of `Install Guix` step? When action is running, you must go to see log immediately. Because github action does not show log after running failed in this case. Don't know why.

I guess you meet issue when `guix pull` (error when connect to GNU website). Yesterday, I already saw this issue many times. 

```
Updating channel 'guix' from Git repository at 'https://git.savannah.gnu.org/git/guix.git'...
guix pull: error: Git error: SSL error: received early EOF
Error: Process completed with exit code 1.
```

**Comment by PromyLOPh** [comment]
Fixed by commit c30721d6f0961406fba1a4c453626e062e93273b

**Pull request closed without merging**
